import { createElement } from 'lwc';
import LWC08_QuickUpdateContact from 'c/lWC08_QuickUpdateContact';

describe('c-l-w-c-08-quick-update-contact', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-08-quick-update-contact', {
            is: LWC08_QuickUpdateContact
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});