import { createElement } from 'lwc';
import Lwc14_SimpleTODO from 'c/lwc14_SimpleTODO';

describe('c-lwc14-simple-todo', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc14-simple-todo', {
            is: Lwc14_SimpleTODO
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});