import { createElement } from 'lwc';
import SECURITY1_OpportunityComponent from 'c/sECURITY1_OpportunityComponent';

describe('c-s-e-c-u-r-i-t-y-1-opportunity-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-s-e-c-u-r-i-t-y-1-opportunity-component', {
            is: SECURITY1_OpportunityComponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});